#to run use: docker-compose run nvim
version: "3"

services:
  nvim:
    build:
      context: https://github.com/madiele/neovim-ide-container.git#main
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - home:/root/

volumes:
  home:
